#!/bin/sh -l

# Generate indices
cd /src
node index.js $GITHUB_WORKSPACE

# Commit and push generated indices
cd $GITHUB_WORKSPACE
git config --global user.email "actions@github.com"
git config --global user.name "$GITHUB_ACTOR"
git add .
git commit -m "Autogenerated indices"
remote_repo="https://x-access-token:${INPUT_CI_AUTH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
git push "${remote_repo}" HEAD:$GITHUB_REF
