#!/bin/sh -l

# Generate indices
cd /
npm ci
node index.js $GITHUB_WORKSPACE

# Commit and push generated indices
cd $GITHUB_WORKSPACE
git config --global user.email "actions@github.com"
git config --global user.name "$GITHUB_ACTOR"
git add .
git commit -m "Autogenerated indices"
git push origin $GITHUB_REF
